server:
  port: 8086
spring:
  config:
    activate:
      on-profile: prod
  cache:
   type: caffeine 		
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
    gateway:
     httpclient:
      pool:
       type: disabled
     discovery:
        locator:
          enabled: true
     routes:
        - id: amazon-service
          uri: lb://amazon-service
          predicates:
            - Path=/api/v1/amazon/**
          filters:
            - AuthFilter  
        - id: warehouse-service
          uri: lb://warehouse-service
          predicates:
            - Path=/api/v1/warehouse/**
          filters:
            - AuthFilter  
        - id: update-service
          uri: lb://update-service
          predicates:
            - Path=/api/v1/updateservice/**
          filters:
            - AuthFilter  
        - id: woocomerce-service
          uri: lb://woocomerce-service
          predicates:
           - Path=/api/v1/woocomerce/**
          filters:
           - AuthFilter
        - id: shopify-service
          uri: lb://shopify-service
          predicates:
           - Path=/api/v1/shopify/**
          filters:
           - AuthFilter
        - id: tasoftware-service
          uri: lb://tasoftware-service
          predicates:
           - Path=/api/v1/tasoftware/**
          filters:
           - AuthFilter	 					 		
        - id: auth-service
          uri: lb://auth-service
          predicates:  
            - Path=/auth/**  
        - id: front-service
          uri: lb://front-service
          predicates:  
            - Path=/app/**  
                 
eureka:
 client:
  fetch-registry: true
  register-with-eureka: true
  serviceUrl:
   defaultZone: http://eurekaServer:8761/eureka
 instance:
  hostname: gateway-service
  instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    
base:
  url:
    authValidate: "http://auth-service:8085/auth/validate"

logging:
 level:
  reactor:
   netty: debug		